
version: '2'
services:
  mariadb:
    image: 'docker.io/bitnami/mariadb:10.3-debian-10'
    volumes:
      - 'mariadb_data:/themanagementfirm/mariadb'
    environment:
      - MARIADB_USER=tmf_wp
      - MARIADB_DATABASE=themanagementfirm_wp
      - ALLOW_EMPTY_PASSWORD=yes
  wordpress:
    image: 'docker.io/themanagementfirm/wp:latest'
    ports:
      - '80:8080'
      - '443:8443'
    volumes:
      - 'wordpress_data:/themanagementfirm/wp'
    depends_on:
      - mariadb
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - WORDPRESS_DATABASE_USER=tmf_wp
      - WORDPRESS_DATABASE_NAME=themanagementfirm_wp
      - ALLOW_EMPTY_PASSWORD=yes
volumes:
  mariadb_data:
    driver: local
  wordpress_data:
    driver: local