#!/bin/bash -e

. /opt/bitnami/base/functions
. /opt/bitnami/base/helpers

print_welcome_page

if [[ "$1" == "nami" && "$2" == "start" ]] || [[ "$1" == "httpd" ]]; then
    . /apache-init.sh
    . /wordpress-init.sh
    nami_initialize apache mysql-client wordpress
    info "Starting gosu... "
    . /post-init.sh
fi

nami_initialize apache php mysql-client wordpress

# Theme Activation
# su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp theme activate pro'
# su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp theme activate pro-child'
# su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp theme activate medizco'
# su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp theme activate medizco-child'
# su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp theme activate phlox-pro'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp theme activate phlox-pro-child'

# Plugin Activation
## Wordpress plugins
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate akismet'
# su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate all-in-one-seo-pack'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate all-in-one-wp-migration'
# su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate amp'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate auxin-elements'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate bbpress'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate buddypress'
# su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate contact-form-7'
# su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate contact-form-7-signature-addon'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate dokan-lite'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate eps-301-redirects'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate google-site-kit'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate intercom'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin deactivate jetpack'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate leadin'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate loginpress'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate mailpoet'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate nomiddleman-crypto-payments-for-woocommerce'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate polylang'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate simple-tags'
# su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate w3-total-cache'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate woocommerce'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate woocommerce-admin'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate woocommerce-services'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate woocommerce-square'
# su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate wp-force-ssl'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate wp-mail-smtp'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate wordpress-seo'

## TMF Hosted Plugins
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate auxin-pro-tools'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate auxin-shop'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate auxin-the-news'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate bdthemes-element-pack'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate dokan-pro'
# su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate dzs-zoomsounds'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate elementor'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate elementor-pro'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate facebook-for-woocommerce'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate go_pricing'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate gp-better-user-activation'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate gp-date-time-calculator'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate gp-date-time-calculator'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate gp-easy-passthrough'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate gp-ecommerce-fields'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate gp-limit-dates'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate gp-live-preview'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate gp-media-library'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate gp-multi-page-navigation'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate gp-nested-forms'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate gp-populate-anything'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate gp-post-content-merge-tags'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate gp-preview-submission'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate gp-unique-id'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate gravityforms'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate gravityforms2checkout'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate gravityformsactivecampaign'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate gravityformsadvancedpostcreation'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate gravityformsagilecrm'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate gravityformsauthorizenet'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate gravityformsaweber'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate gravityformsbreeze'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate gravityformscampaignmonitor'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate gravityformschainedselects'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate gravityformscleverreach'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate gravityformscli'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate gravityformsconstantcontact'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate gravityformscoupons'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate gravityformsdropbox'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate gravityformsemailoctopus'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate gravityformsfreshbooks'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate gravityformsgetresponse'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate gravityformshelpscout'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate gravityformshubspot'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate gravityformsicontact'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate gravityformsmadmimi'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate gravityformsmailchimp'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate gravityformsmailgun'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate gravityformsmollie'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate gravityformspartialentries'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate gravityformspaypal'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate gravityformspaypalpaymentspro'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate gravityformspipe'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate gravityformspolls'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate gravityformspostmark'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate gravityformsppcp'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate gravityformsquiz'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate gravityformssendgrid'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate gravityformssignature'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate gravityformsslack'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate gravityformsstripe'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate gravityformssurvey'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate gravityformstrello'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate gravityformstwilio'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate gravityformsuserregistration'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate gravityformswebhooks'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate gravityformszapier'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate gravityformszohocrm'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate gravityperks'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate gwcommentblacklist'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate gwcommentblacklist'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate gwconditionalpricing'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate gwcopycat'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate gwemailusers'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate gwexpandtextareas'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate gwlimitcheckboxes'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate gwlimitchoices'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate gwpaypalonetimefee'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate gwpayperword'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate gwpricerange'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate gwreadonly'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate gwreloadform'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate gwtermsofservice'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate gwwordcount'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate highways-sync-for-intercom'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate js_composer'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate LayerSlider'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate masterslider'
# su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate medizco-essential'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate polylang-pro'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate polylang-wc'
# su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate qube'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate revslider'
#su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate shift-cv'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate Ultimate_VC_Addons'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate waspthemes-yellow-pencil'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate woocommerce-bookings'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate woocommerce-gateway-amazon-payments-advanced'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate woocommerce-gravityforms-product-addons'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate woocommerce-gift-cards'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate woocommerce-payments'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate woocommerce-product-addons'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate woocommerce-product-bundles'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate woocommerce-subscriptions'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate woocommerce-subscription-downloads'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate wp-mail-smtp'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate wp-rocket'
# su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate wp-seo-premium'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate wpseo-local'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate wpseo-news'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate wpseo-video'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate wpseo-woocommerce'

## Themeco Hosted Plugins (Pro Theme Specific)
# su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate convertplug'
# su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate tco-custom-404'
# su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate tco-disqus-comments'
# su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate tco-email-forms'
# su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate envira-gallery'
# su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate essential-grid'
# su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate tco-facebook-comments'
# su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate tco-google-analytics'
# su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate modern-events-calendar'
# su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate tco-olark-integration'
# su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate tco-smooth-scroll'
# su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate snippet'
# su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate soliloquy'
# su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate superfly-menu'
# su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate tco-terms-of-use'
# su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate the-grid'
# su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate ubermenu'
# su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate tco-under-construction'
# su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate tco-video-lock'
# su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate tco-white-label'
# su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate tco-woo-checkout-editor'
# su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate tco-content-dock'
# su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate WP_Estimation_Form'
# su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate advanced-custom-fields-pro'
# su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate all-in-one-seo-pack'
# su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate contact-form-7-signature-addon'
# su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate simple-tags'
# su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate google-site-kit'
# su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate woocommerce-gift-cards'
# su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate woocommerce-services'

info "Starting wordpress... "

exec tini -- "$@"